-- =============================================================
-- ALTERACOES - MODULO FILAMENTOS
-- Objetivo:
-- 1) Criar tabela de fabricantes de filamentos.
-- 2) Popular fabricantes conhecidos.
-- 3) Relacionar cadastro_filamentos com fabricantes.
-- 4) Manter materiais como lista controlada no front-end.
-- =============================================================

CREATE TABLE IF NOT EXISTS public.cadastro_fabricantes_filamentos (
    id_fabricante_filamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_fabricante TEXT NOT NULL UNIQUE,
    site_fabricante TEXT NULL,
    observacoes TEXT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.cadastro_fabricantes_filamentos (nome_fabricante, ativo)
VALUES
    ('3D Fila', TRUE),
    ('3D Lab', TRUE),
    ('Anycubic', TRUE),
    ('Creality', TRUE),
    ('Elegoo', TRUE),
    ('Esun', TRUE),
    ('Voolt3D', TRUE),
    ('Bambu Lab', TRUE),
    ('Prusa Research', TRUE),
    ('Polymaker', TRUE),
    ('Sunlu', TRUE),
    ('Kingroon', TRUE),
    ('Overture', TRUE),
    ('ColorFabb', TRUE),
    ('Fillamentum', TRUE),
    ('Raise3D', TRUE),
    ('FormFutura', TRUE),
    ('Fiberlogy', TRUE),
    ('MatterHackers', TRUE),
    ('Flashforge', TRUE),
    ('Outro', TRUE)
ON CONFLICT (nome_fabricante) DO NOTHING;

ALTER TABLE public.cadastro_filamentos
ADD COLUMN IF NOT EXISTS id_fabricante_filamento BIGINT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_schema = 'public'
          AND table_name = 'cadastro_filamentos'
          AND constraint_name = 'cadastro_filamentos_id_fabricante_filamento_fkey'
    ) THEN
        ALTER TABLE public.cadastro_filamentos
        ADD CONSTRAINT cadastro_filamentos_id_fabricante_filamento_fkey
        FOREIGN KEY (id_fabricante_filamento)
        REFERENCES public.cadastro_fabricantes_filamentos(id_fabricante_filamento)
        ON UPDATE CASCADE
        ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_cadastro_filamentos_id_fabricante_filamento
ON public.cadastro_filamentos(id_fabricante_filamento);

ALTER TABLE public.cadastro_fabricantes_filamentos ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'cadastro_fabricantes_filamentos'
          AND policyname = 'cadastro_fabricantes_filamentos_select'
    ) THEN
        CREATE POLICY cadastro_fabricantes_filamentos_select
        ON public.cadastro_fabricantes_filamentos
        FOR SELECT
        USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'cadastro_fabricantes_filamentos'
          AND policyname = 'cadastro_fabricantes_filamentos_insert'
    ) THEN
        CREATE POLICY cadastro_fabricantes_filamentos_insert
        ON public.cadastro_fabricantes_filamentos
        FOR INSERT
        WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'cadastro_fabricantes_filamentos'
          AND policyname = 'cadastro_fabricantes_filamentos_update'
    ) THEN
        CREATE POLICY cadastro_fabricantes_filamentos_update
        ON public.cadastro_fabricantes_filamentos
        FOR UPDATE
        USING (true)
        WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'cadastro_fabricantes_filamentos'
          AND policyname = 'cadastro_fabricantes_filamentos_delete'
    ) THEN
        CREATE POLICY cadastro_fabricantes_filamentos_delete
        ON public.cadastro_fabricantes_filamentos
        FOR DELETE
        USING (true);
    END IF;
END $$;
